Console.WriteLine("TIPO DE ATENCIÓN");
Console.WriteLine(" 1: Emergencia");
Console.WriteLine(" 2: Consulta");
Console.WriteLine(" 3: Pediatría");
Console.WriteLine(" 4: Traumatología");
Console.WriteLine("Ingresar opción: ");
int option = int.Parse(Console.ReadLine());
Console.WriteLine("Ingresar temperatura:");
double temperatura = double.Parse(Console.ReadLine());
Console.WriteLine("Ingresar saturación de oxígeno:");
double saturacion = double.Parse(Console.ReadLine());
Console.WriteLine("Ingresar nivel de dolor (0-10)");
int dolor = int.Parse(Console.ReadLine());
Console.WriteLine("Ingresar presión sistólica");
double presion = double.Parse(Console.ReadLine());
